#!/bin/zsh
#
#  Copyright 2013 Robert Welin
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generates the trust stores for the server (keystore.jks) and the client (public_truststore.bks)

KEYSTORE=keystore.jks
CERT=public.cert
PUBLIC=public_keystore.bks

if [ $# -eq 0 ]; then
    echo 'gentruststores - Generates the trust stores for the server (keystore.jks) and the app (public_truststore.bks)

USAGE:
    gentruststores <truststore password> <path to BouncyCastleProvider jar file>

EXAMPLE:
    gentruststores testpassword ~/Downloads/bcprov-jdk16-146.jar'
    exit 0
fi

PASSWORD="$1"

# Generate public/private keys and certificate
if [ -e $KEYSTORE ]; then
    rm $KEYSTORE
fi
keytool -genkey -keyalg RSA -alias selfsigned -keystore $KEYSTORE -storepass $PASSWORD -validity 365 -keysize 2048

# Export cert
if [ -e $CERT ]; then
    rm $CERT
fi
keytool -export -alias selfsigned -keystore $KEYSTORE -storepass $PASSWORD -rfc -file $CERT

# Generate public key and cert
if [ -e $PUBLIC ]; then
    rm $PUBLIC
fi
keytool -import -alias selfsigned -file $CERT -storetype BKS -providerclass org.bouncycastle.jce.provider.BouncyCastleProvider -providerpath "$2" -rfc -file $CERT -keystore $PUBLIC -storepass $PASSWORD

# Clean up
if [ -e $CERT ]; then
    rm $CERT
fi
